CREATE DATABASE IF NOT EXISTS whatsapp_views;
USE whatsapp_views;

CREATE TABLE IF NOT EXISTS contacts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  number VARCHAR(20) NOT NULL UNIQUE,
  date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
